version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: devops/Dockerfile
    expose:
      - "8081"
    volumes:
      - ./source:/app/source
      - ./dub.json:/app/dub.json
    environment:
      - DUB_HTTP_PROXY=
    command: dub run
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      replicas: 5  # Run 5 instances of the app
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  k6:
    image: grafana/k6:latest
    user: root
    volumes:
      - ./k6:/scripts
    networks:
      - app-network
    command: run /scripts/app-up.js
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge